# Generated by Django 4.0.4 on 2022-04-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cortes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='cortes')),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
