# Generated by Django 4.0.4 on 2022-04-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_app', '0002_cortes_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='cortes')),
            ],
        ),
        migrations.DeleteModel(
            name='Cortes',
        ),
    ]
