# Generated by Django 4.0.4 on 2022-04-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber_app', '0002_alter_citas_nombre_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='turno',
        ),
    ]
